name: CI/CD

on: 
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest
        
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js >= 10
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    
    - name: Install dependecies
      run: |
        npm install
    
    - name: Add remote origin
      env:
        API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        git remote add heroku https://heroku:$API_KEY@git.heroku.com/bcmodapi.git

    - name: Deploy to Heroku
      run: |
        git push heroku master
